# Generated by Django 5.1.4 on 2024-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='otp_checks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
