# Generated by Django 5.1.4 on 2025-01-05 14:19

import otps.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp_type', models.CharField(choices=[('customer_login', 'Customer Login'), ('admin_login', 'Admin Login'), ('admin_register', 'Admin Register'), ('password_change', 'Password change')], max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_attemps', models.PositiveIntegerField(default=0)),
                ('otp_checks', models.PositiveIntegerField(default=0)),
                ('otp_expiry', models.DateTimeField(default=otps.defaults.default_otp_expiry)),
                ('otp_attemps_expiry', models.DateTimeField(default=otps.defaults.default_otp_attemps_expiry)),
            ],
        ),
    ]
