# Generated by Django 5.1.4 on 2025-04-22 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_carts', to=settings.AUTH_USER_MODEL),
        ),
    ]
