# Generated by Django 5.1.4 on 2025-04-22 00:17

import otps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(choices=[('customer_login', 'Customer Login'), ('admin_login', 'Admin Login'), ('admin_register', 'Admin Register'), ('password_change', 'Password change')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('attemps', models.PositiveIntegerField(default=0)),
                ('cheks', models.PositiveIntegerField(default=0)),
                ('expiry', models.DateTimeField(default=otps.utils.default_otp_expiry)),
                ('attemps_expiry', models.DateTimeField(default=otps.utils.default_otp_attemps_expiry)),
            ],
        ),
    ]
