# Generated by Django 5.1.4 on 2025-04-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='cheks',
            new_name='checks',
        ),
    ]
