# Generated by Django 5.1.4 on 2025-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otps', '0002_rename_cheks_otprequest_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='type',
            field=models.CharField(choices=[('user_login', 'User Login'), ('admin_login', 'Admin Login'), ('admin_register', 'Admin Register'), ('password_change', 'Password change')], max_length=20),
        ),
    ]
