# Generated by Django 5.1.4 on 2025-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_productimage_productadditionalimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
