# Generated by Django 5.1.4 on 2025-01-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_slug_alter_productbrand_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionCountry',
            new_name='ProductCountry',
        ),
    ]
